version: '3'

services:
  mysql:
    # build: ./dockerfiles/mysql
    image: mysql:5.7
    container_name: gpshelp-mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=gpshelp
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=topsecret
      - MYSQL_PORT=3306
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql_db:/var/lib/mysql

  redis:
    image: "redis:alpine"
    container_name: gpshelp-redis
      # command: redis-server --requirepass redispassword
    ports:
      - "6380:6379"